spring.application.name=spring-ai-demo
server.port=8080

# api key for open ai
spring.ai.openai.api-key=${OPENAI_API_KEY}


# for multiple Chat models: we don't want to enable or create a bean for both AI chat models.
spring.ai.chat.client.enabled=fasle

# Ollama Properties
spring.ai.ollama.base-url=http://localhost:11434/
spring.ai.ollama.chat.options.model=phi3:latest
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.chat.options.max-tokens=50

logging.level.org.springframework.ai.chat.client.advisor= DEBUG
